baseurl = "http://www.anthonyfalzetti.com"
title = "Anthony Falzetti"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
pygmentsUseClasses = true
disqusShortname = "Anthony"
paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Anthony Falzetti"
  info = "Software Engineer"
  description = "Anthony Falzetti's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/anthonyfalzetti.jpeg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"
  since = 2023
  enableTwemoji = true
  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/anthonyfalzetti/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/anthonyfalzetti/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "blog/"